apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciandk3s
  namespace: hwankoo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciandk3s
  template:
    metadata:
      labels:
        app: ciandk3s
    spec:
      containers:
        - name: ciandk3s
          image: ghcr.io/hwan-koo/ciandk3s:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
          - name: log-volume
            mountPath: /var/log/edu
      volumes:
      - name: log-volume
        hostPath:
          path: /logs/hwankoo  # 본인의 namespace로 변경하세요
          type: DirectoryOrCreate
