name: Publish Nexus GitHub image

on:      
  workflow_dispatch:
    inputs:
      name:
        description: "Docker TAG"
        required: true
        default: "master"
env:
  NEXUS_REGISTRY: localhost:5443  # Nexus 레지스트리 URL과 포트
  GHCR_REGISTRY: ghcr.io  # GitHub Container Registry URL
  IMAGE_NAME: ciandk3s  # 이미지 이름
  GITHUB_REPOSITORY: ${{ github.repository }}  # GitHub 리포지토리 이름

jobs:
  build-and-sync:
    runs-on: self-hosted


    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3



      # 3. Setup Docker buildx
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # 4. Log into Nexus registry to push the image
      - name: Log into Nexus registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.NEXUS_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}  # Nexus 레지스트리 사용자 이름
          password: ${{ secrets.NEXUS_PASSWORD }}  # Nexus 레지스트리 비밀번호

      # 5. Build and push Docker image to Nexus
      - name: Build and push Docker image to Nexus
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.NEXUS_REGISTRY }}/repository/${{ env.IMAGE_NAME }}:latest

      # 6. Log into Nexus registry to pull the image (again, to sync with GHCR)
      - name: Log into Nexus registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.NEXUS_REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      # 7. Pull Docker image from Nexus
      - name: Pull Docker image from Nexus
        run: |
          docker pull ${{ env.NEXUS_REGISTRY }}/repository/${{ env.IMAGE_NAME }}:latest

      # 8. Log into GitHub Container Registry (GHCR)
      - name: Log into GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}  # GitHub에서 제공하는 actor (현재 작업자)
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHub 토큰

      # 9. Tag the pulled image for GitHub Container Registry
      - name: Tag Docker image for GHCR
        run: |
          docker tag ${{ env.NEXUS_REGISTRY }}/repository/${{ env.IMAGE_NAME }}:latest ${{ env.GHCR_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest

      # 10. Push Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ${{ env.GHCR_REGISTRY }}/${{ env.GITHUB_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
